
var http = require('http');
var dt = require('./myfirstmodule');
var url = require('url');

http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/html'});
  res.write('Hello World!')
  res.write('\nThe current date and time are currently: ' + dt.myDateTime());
  res.write('\n' + req.url);
  var q = url.parse(req.url, true).query;
  var txt = q.year + ' ' + q.month;
  res.write('\n' + txt);
  res.end();
}).listen(8191);

// request looks like:

//{ _readableState:
//   { objectMode: false,
//     highWaterMark: 16384,
//     buffer: [],
//     length: 0,
//     pipes: null,
//     pipesCount: 0,
//     flowing: null,
//     ended: false,
//     endEmitted: false,
//     reading: false,
//     sync: true,
//     needReadable: false,
//     emittedReadable: false,
//     readableListening: false,
//     defaultEncoding: 'utf8',
//     ranOut: false,
//     awaitDrain: 0,
//     readingMore: false,
//     decoder: null,
//     encoding: null },
//  readable: true,
//  domain: null,
//  _events: {},
//  _maxListeners: undefined,
//  socket:
//   { _connecting: false,
//     _hadError: false,
//     _handle:
//      { fd: 12,
//        reading: true,
//        owner: [Circular],
//        onread: [Function: onread],
//        onconnection: null,
//        writeQueueSize: 0 },
//     _parent: null,
//     _host: null,
//     _readableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        buffer: [],
//        length: 0,
//        pipes: null,
//        pipesCount: 0,
//        flowing: true,
//        ended: false,
//        endEmitted: false,
//        reading: false,
//        sync: false,
//        needReadable: true,
//        emittedReadable: false,
//        readableListening: false,
//        defaultEncoding: 'utf8',
//        ranOut: false,
//        awaitDrain: 0,
//        readingMore: false,
//        decoder: null,
//        encoding: null,
//        resumeScheduled: false },
//     readable: true,
//     domain: null,
//     _events:
//      { end: [Object],
//        finish: [Function: onSocketFinish],
//        _socketEnd: [Function: onSocketEnd],
//        drain: [Object],
//        timeout: [Function],
//        error: [Function: socketOnError],
//        close: [Object],
//        data: [Function: socketOnData] },
//     _maxListeners: undefined,
//     _writableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        needDrain: false,
//        ending: false,
//        ended: false,
//        finished: false,
//        decodeStrings: false,
//        defaultEncoding: 'utf8',
//        length: 0,
//        writing: false,
//        corked: 0,
//        sync: false,
//        bufferProcessing: false,
//        onwrite: [Function],
//        writecb: null,
//        writelen: 0,
//        bufferedRequest: null,
//        lastBufferedRequest: null,
//        pendingcb: 3,
//        prefinished: false,
//        errorEmitted: false },
//     writable: true,
//     allowHalfOpen: true,
//     destroyed: false,
//     bytesRead: 457,
//     _bytesDispatched: 266,
//     _pendingData: null,
//     _pendingEncoding: '',
//     server:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        _connections: 3,
//        _handle: [Object],
//        _usingSlaves: false,
//        _slaves: [],
//        allowHalfOpen: true,
//        pauseOnConnect: false,
//        httpAllowHalfOpen: false,
//        timeout: 120000,
//        _connectionKey: '4:null:8191' },
//     _idleTimeout: 120000,
//     _idleNext:
//      { [Function: utcDate]
//        _onTimeout: [Function],
//        _idleTimeout: 497,
//        _idleNext: [Object],
//        _idlePrev: [Circular],
//        _idleStart: 207393822 },
//     _idlePrev: { _idleNext: [Circular], _idlePrev: [Object] },
//     _idleStart: 207393825,
//     parser:
//      { '0': [Function: parserOnHeaders],
//        '1': [Function: parserOnHeadersComplete],
//        '2': [Function: parserOnBody],
//        '3': [Function: parserOnMessageComplete],
//        _headers: [],
//        _url: '',
//        socket: [Circular],
//        incoming: [Circular],
//        maxHeaderPairs: 2000,
//        onIncoming: [Function: parserOnIncoming] },
//     _paused: false,
//     read: [Function],
//     _consuming: true,
//     _httpMessage:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        output: [],
//        outputEncodings: [],
//        outputCallbacks: [],
//        writable: true,
//        _last: false,
//        chunkedEncoding: true,
//        shouldKeepAlive: true,
//        useChunkedEncodingByDefault: true,
//        sendDate: true,
//        _removedHeader: {},
//        _hasBody: true,
//        _trailer: '',
//        finished: false,
//        _hangupClose: false,
//        _headerSent: true,
//        socket: [Circular],
//        connection: [Circular],
//        _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nDate: Thu, 28 Sep 2017 13:04:35 GMT\r\nConnection: keep-alive\r\nTransfer-Encoding: chunked\r\n\r\n',
//        _headers: null,
//        _headerNames: {},
//        statusMessage: 'OK',
//        statusCode: 200 } },
//  connection:
//   { _connecting: false,
//     _hadError: false,
//     _handle:
//      { fd: 12,
//        reading: true,
//        owner: [Circular],
//        onread: [Function: onread],
//        onconnection: null,
//        writeQueueSize: 0 },
//     _parent: null,
//     _host: null,
//     _readableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        buffer: [],
//        length: 0,
//        pipes: null,
//        pipesCount: 0,
//        flowing: true,
//        ended: false,
//        endEmitted: false,
//        reading: false,
//        sync: false,
//        needReadable: true,
//        emittedReadable: false,
//        readableListening: false,
//        defaultEncoding: 'utf8',
//        ranOut: false,
//        awaitDrain: 0,
//        readingMore: false,
//        decoder: null,
//        encoding: null,
//        resumeScheduled: false },
//     readable: true,
//     domain: null,
//     _events:
//      { end: [Object],
//        finish: [Function: onSocketFinish],
//        _socketEnd: [Function: onSocketEnd],
//        drain: [Object],
//        timeout: [Function],
//        error: [Function: socketOnError],
//        close: [Object],
//        data: [Function: socketOnData] },
//     _maxListeners: undefined,
//     _writableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        needDrain: false,
//        ending: false,
//        ended: false,
//        finished: false,
//        decodeStrings: false,
//        defaultEncoding: 'utf8',
//        length: 0,
//        writing: false,
//        corked: 0,
//        sync: false,
//        bufferProcessing: false,
//        onwrite: [Function],
//        writecb: null,
//        writelen: 0,
//        bufferedRequest: null,
//        lastBufferedRequest: null,
//        pendingcb: 3,
//        prefinished: false,
//        errorEmitted: false },
//     writable: true,
//     allowHalfOpen: true,
//     destroyed: false,
//     bytesRead: 457,
//     _bytesDispatched: 266,
//     _pendingData: null,
//     _pendingEncoding: '',
//     server:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        _connections: 3,
//        _handle: [Object],
//        _usingSlaves: false,
//        _slaves: [],
//        allowHalfOpen: true,
//        pauseOnConnect: false,
//        httpAllowHalfOpen: false,
//        timeout: 120000,
//        _connectionKey: '4:null:8191' },
//     _idleTimeout: 120000,
//     _idleNext:
//      { [Function: utcDate]
//        _onTimeout: [Function],
//        _idleTimeout: 497,
//        _idleNext: [Object],
//        _idlePrev: [Circular],
//        _idleStart: 207393822 },
//     _idlePrev: { _idleNext: [Circular], _idlePrev: [Object] },
//     _idleStart: 207393825,
//     parser:
//      { '0': [Function: parserOnHeaders],
//        '1': [Function: parserOnHeadersComplete],
//        '2': [Function: parserOnBody],
//        '3': [Function: parserOnMessageComplete],
//        _headers: [],
//        _url: '',
//        socket: [Circular],
//        incoming: [Circular],
//        maxHeaderPairs: 2000,
//        onIncoming: [Function: parserOnIncoming] },
//     _paused: false,
//     read: [Function],
//     _consuming: true,
//     _httpMessage:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        output: [],
//        outputEncodings: [],
//        outputCallbacks: [],
//        writable: true,
//        _last: false,
//        chunkedEncoding: true,
//        shouldKeepAlive: true,
//        useChunkedEncodingByDefault: true,
//        sendDate: true,
//        _removedHeader: {},
//        _hasBody: true,
//        _trailer: '',
//        finished: false,
//        _hangupClose: false,
//        _headerSent: true,
//        socket: [Circular],
//        connection: [Circular],
//        _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nDate: Thu, 28 Sep 2017 13:04:35 GMT\r\nConnection: keep-alive\r\nTransfer-Encoding: chunked\r\n\r\n',
//        _headers: null,
//        _headerNames: {},
//        statusMessage: 'OK',
//        statusCode: 200 } },
//  httpVersionMajor: 1,
//  httpVersionMinor: 1,
//  httpVersion: '1.1',
//  complete: false,
//  headers:
//   { host: 'localhost:8191',
//     connection: 'keep-alive',
//     'cache-control': 'max-age=0',
//     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
//     'upgrade-insecure-requests': '1',
//     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
//     dnt: '1',
//     'accept-encoding': 'gzip, deflate, br',
//     'accept-language': 'en-US,en;q=0.8,fr;q=0.6' },
//  rawHeaders:
//   [ 'Host',
//     'localhost:8191',
//     'Connection',
//     'keep-alive',
//     'Cache-Control',
//     'max-age=0',
//     'User-Agent',
//     'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
//     'Upgrade-Insecure-Requests',
//     '1',
//     'Accept',
//     'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
//     'DNT',
//     '1',
//     'Accept-Encoding',
//     'gzip, deflate, br',
//     'Accept-Language',
//     'en-US,en;q=0.8,fr;q=0.6' ],
//  trailers: {},
//  rawTrailers: [],
//  _pendings: [],
//  _pendingIndex: 0,
//  upgrade: false,
//  url: '/?year=2017&month=July',
//  method: 'GET',
//  statusCode: null,
//  statusMessage: null,
//  client:
//   { _connecting: false,
//     _hadError: false,
//     _handle:
//      { fd: 12,
//        reading: true,
//        owner: [Circular],
//        onread: [Function: onread],
//        onconnection: null,
//        writeQueueSize: 0 },
//     _parent: null,
//     _host: null,
//     _readableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        buffer: [],
//        length: 0,
//        pipes: null,
//        pipesCount: 0,
//        flowing: true,
//        ended: false,
//        endEmitted: false,
//        reading: false,
//        sync: false,
//        needReadable: true,
//        emittedReadable: false,
//        readableListening: false,
//        defaultEncoding: 'utf8',
//        ranOut: false,
//        awaitDrain: 0,
//        readingMore: false,
//        decoder: null,
//        encoding: null,
//        resumeScheduled: false },
//     readable: true,
//     domain: null,
//     _events:
//      { end: [Object],
//        finish: [Function: onSocketFinish],
//        _socketEnd: [Function: onSocketEnd],
//        drain: [Object],
//        timeout: [Function],
//        error: [Function: socketOnError],
//        close: [Object],
//        data: [Function: socketOnData] },
//     _maxListeners: undefined,
//     _writableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        needDrain: false,
//        ending: false,
//        ended: false,
//        finished: false,
//        decodeStrings: false,
//        defaultEncoding: 'utf8',
//        length: 0,
//        writing: false,
//        corked: 0,
//        sync: false,
//        bufferProcessing: false,
//        onwrite: [Function],
//        writecb: null,
//        writelen: 0,
//        bufferedRequest: null,
//        lastBufferedRequest: null,
//        pendingcb: 3,
//        prefinished: false,
//        errorEmitted: false },
//     writable: true,
//     allowHalfOpen: true,
//     destroyed: false,
//     bytesRead: 457,
//     _bytesDispatched: 266,
//     _pendingData: null,
//     _pendingEncoding: '',
//     server:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        _connections: 3,
//        _handle: [Object],
//        _usingSlaves: false,
//        _slaves: [],
//        allowHalfOpen: true,
//        pauseOnConnect: false,
//        httpAllowHalfOpen: false,
//        timeout: 120000,
//        _connectionKey: '4:null:8191' },
//     _idleTimeout: 120000,
//     _idleNext:
//      { [Function: utcDate]
//        _onTimeout: [Function],
//        _idleTimeout: 497,
//        _idleNext: [Object],
//        _idlePrev: [Circular],
//        _idleStart: 207393822 },
//     _idlePrev: { _idleNext: [Circular], _idlePrev: [Object] },
//     _idleStart: 207393825,
//     parser:
//      { '0': [Function: parserOnHeaders],
//        '1': [Function: parserOnHeadersComplete],
//        '2': [Function: parserOnBody],
//        '3': [Function: parserOnMessageComplete],
//        _headers: [],
//        _url: '',
//        socket: [Circular],
//        incoming: [Circular],
//        maxHeaderPairs: 2000,
//        onIncoming: [Function: parserOnIncoming] },
//     _paused: false,
//     read: [Function],
//     _consuming: true,
//     _httpMessage:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        output: [],
//        outputEncodings: [],
//        outputCallbacks: [],
//        writable: true,
//        _last: false,
//        chunkedEncoding: true,
//        shouldKeepAlive: true,
//        useChunkedEncodingByDefault: true,
//        sendDate: true,
//        _removedHeader: {},
//        _hasBody: true,
//        _trailer: '',
//        finished: false,
//        _hangupClose: false,
//        _headerSent: true,
//        socket: [Circular],
//        connection: [Circular],
//        _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nDate: Thu, 28 Sep 2017 13:04:35 GMT\r\nConnection: keep-alive\r\nTransfer-Encoding: chunked\r\n\r\n',
//        _headers: null,
//        _headerNames: {},
//        statusMessage: 'OK',
//        statusCode: 200 } },
//  _consuming: false,
//  _dumped: false }
//{ year: '2017', month: 'July' }
//{ _readableState:
//   { objectMode: false,
//     highWaterMark: 16384,
//     buffer: [],
//     length: 0,
//     pipes: null,
//     pipesCount: 0,
//     flowing: null,
//     ended: false,
//     endEmitted: false,
//     reading: false,
//     sync: true,
//     needReadable: false,
//     emittedReadable: false,
//     readableListening: false,
//     defaultEncoding: 'utf8',
//     ranOut: false,
//     awaitDrain: 0,
//     readingMore: false,
//     decoder: null,
//     encoding: null },
//  readable: true,
//  domain: null,
//  _events: {},
//  _maxListeners: undefined,
//  socket:
//   { _connecting: false,
//     _hadError: false,
//     _handle:
//      { fd: 12,
//        reading: true,
//        owner: [Circular],
//        onread: [Function: onread],
//        onconnection: null,
//        writeQueueSize: 0 },
//     _parent: null,
//     _host: null,
//     _readableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        buffer: [],
//        length: 0,
//        pipes: null,
//        pipesCount: 0,
//        flowing: true,
//        ended: false,
//        endEmitted: false,
//        reading: false,
//        sync: false,
//        needReadable: true,
//        emittedReadable: false,
//        readableListening: false,
//        defaultEncoding: 'utf8',
//        ranOut: false,
//        awaitDrain: 0,
//        readingMore: false,
//        decoder: null,
//        encoding: null,
//        resumeScheduled: false },
//     readable: true,
//     domain: null,
//     _events:
//      { end: [Object],
//        finish: [Function: onSocketFinish],
//        _socketEnd: [Function: onSocketEnd],
//        drain: [Object],
//        timeout: [Function],
//        error: [Function: socketOnError],
//        close: [Object],
//        data: [Function: socketOnData] },
//     _maxListeners: undefined,
//     _writableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        needDrain: false,
//        ending: false,
//        ended: false,
//        finished: false,
//        decodeStrings: false,
//        defaultEncoding: 'utf8',
//        length: 0,
//        writing: false,
//        corked: 0,
//        sync: false,
//        bufferProcessing: false,
//        onwrite: [Function],
//        writecb: null,
//        writelen: 0,
//        bufferedRequest: null,
//        lastBufferedRequest: null,
//        pendingcb: 3,
//        prefinished: false,
//        errorEmitted: false },
//     writable: true,
//     allowHalfOpen: true,
//     destroyed: false,
//     bytesRead: 899,
//     _bytesDispatched: 541,
//     _pendingData: null,
//     _pendingEncoding: '',
//     server:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        _connections: 3,
//        _handle: [Object],
//        _usingSlaves: false,
//        _slaves: [],
//        allowHalfOpen: true,
//        pauseOnConnect: false,
//        httpAllowHalfOpen: false,
//        timeout: 120000,
//        _connectionKey: '4:null:8191' },
//     _idleTimeout: 120000,
//     _idleNext:
//      { [Function: utcDate]
//        _onTimeout: [Function],
//        _idleTimeout: 497,
//        _idleNext: [Object],
//        _idlePrev: [Circular],
//        _idleStart: 207393822 },
//     _idlePrev: { _idleNext: [Circular], _idlePrev: [Object] },
//     _idleStart: 207394207,
//     parser:
//      { '0': [Function: parserOnHeaders],
//        '1': [Function: parserOnHeadersComplete],
//        '2': [Function: parserOnBody],
//        '3': [Function: parserOnMessageComplete],
//        _headers: [],
//        _url: '',
//        socket: [Circular],
//        incoming: [Circular],
//        maxHeaderPairs: 2000,
//        onIncoming: [Function: parserOnIncoming] },
//     _paused: false,
//     read: [Function],
//     _consuming: true,
//     _httpMessage:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        output: [],
//        outputEncodings: [],
//        outputCallbacks: [],
//        writable: true,
//        _last: false,
//        chunkedEncoding: true,
//        shouldKeepAlive: true,
//        useChunkedEncodingByDefault: true,
//        sendDate: true,
//        _removedHeader: {},
//        _hasBody: true,
//        _trailer: '',
//        finished: false,
//        _hangupClose: false,
//        _headerSent: true,
//        socket: [Circular],
//        connection: [Circular],
//        _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nDate: Thu, 28 Sep 2017 13:04:35 GMT\r\nConnection: keep-alive\r\nTransfer-Encoding: chunked\r\n\r\n',
//        _headers: null,
//        _headerNames: {},
//        statusMessage: 'OK',
//        statusCode: 200 } },
//  connection:
//   { _connecting: false,
//     _hadError: false,
//     _handle:
//      { fd: 12,
//        reading: true,
//        owner: [Circular],
//        onread: [Function: onread],
//        onconnection: null,
//        writeQueueSize: 0 },
//     _parent: null,
//     _host: null,
//     _readableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        buffer: [],
//        length: 0,
//        pipes: null,
//        pipesCount: 0,
//        flowing: true,
//        ended: false,
//        endEmitted: false,
//        reading: false,
//        sync: false,
//        needReadable: true,
//        emittedReadable: false,
//        readableListening: false,
//        defaultEncoding: 'utf8',
//        ranOut: false,
//        awaitDrain: 0,
//        readingMore: false,
//        decoder: null,
//        encoding: null,
//        resumeScheduled: false },
//     readable: true,
//     domain: null,
//     _events:
//      { end: [Object],
//        finish: [Function: onSocketFinish],
//        _socketEnd: [Function: onSocketEnd],
//        drain: [Object],
//        timeout: [Function],
//        error: [Function: socketOnError],
//        close: [Object],
//        data: [Function: socketOnData] },
//     _maxListeners: undefined,
//     _writableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        needDrain: false,
//        ending: false,
//        ended: false,
//        finished: false,
//        decodeStrings: false,
//        defaultEncoding: 'utf8',
//        length: 0,
//        writing: false,
//        corked: 0,
//        sync: false,
//        bufferProcessing: false,
//        onwrite: [Function],
//        writecb: null,
//        writelen: 0,
//        bufferedRequest: null,
//        lastBufferedRequest: null,
//        pendingcb: 3,
//        prefinished: false,
//        errorEmitted: false },
//     writable: true,
//     allowHalfOpen: true,
//     destroyed: false,
//     bytesRead: 899,
//     _bytesDispatched: 541,
//     _pendingData: null,
//     _pendingEncoding: '',
//     server:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        _connections: 3,
//        _handle: [Object],
//        _usingSlaves: false,
//        _slaves: [],
//        allowHalfOpen: true,
//        pauseOnConnect: false,
//        httpAllowHalfOpen: false,
//        timeout: 120000,
//        _connectionKey: '4:null:8191' },
//     _idleTimeout: 120000,
//     _idleNext:
//      { [Function: utcDate]
//        _onTimeout: [Function],
//        _idleTimeout: 497,
//        _idleNext: [Object],
//        _idlePrev: [Circular],
//        _idleStart: 207393822 },
//     _idlePrev: { _idleNext: [Circular], _idlePrev: [Object] },
//     _idleStart: 207394207,
//     parser:
//      { '0': [Function: parserOnHeaders],
//        '1': [Function: parserOnHeadersComplete],
//        '2': [Function: parserOnBody],
//        '3': [Function: parserOnMessageComplete],
//        _headers: [],
//        _url: '',
//        socket: [Circular],
//        incoming: [Circular],
//        maxHeaderPairs: 2000,
//        onIncoming: [Function: parserOnIncoming] },
//     _paused: false,
//     read: [Function],
//     _consuming: true,
//     _httpMessage:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        output: [],
//        outputEncodings: [],
//        outputCallbacks: [],
//        writable: true,
//        _last: false,
//        chunkedEncoding: true,
//        shouldKeepAlive: true,
//        useChunkedEncodingByDefault: true,
//        sendDate: true,
//        _removedHeader: {},
//        _hasBody: true,
//        _trailer: '',
//        finished: false,
//        _hangupClose: false,
//        _headerSent: true,
//        socket: [Circular],
//        connection: [Circular],
//        _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nDate: Thu, 28 Sep 2017 13:04:35 GMT\r\nConnection: keep-alive\r\nTransfer-Encoding: chunked\r\n\r\n',
//        _headers: null,
//        _headerNames: {},
//        statusMessage: 'OK',
//        statusCode: 200 } },
//  httpVersionMajor: 1,
//  httpVersionMinor: 1,
//  httpVersion: '1.1',
//  complete: false,
//  headers:
//   { host: 'localhost:8191',
//     connection: 'keep-alive',
//     pragma: 'no-cache',
//     'cache-control': 'no-cache',
//     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
//     accept: 'image/webp,image/apng,image/*,*/*;q=0.8',
//     dnt: '1',
//     referer: 'http://localhost:8191/?year=2017&month=July',
//     'accept-encoding': 'gzip, deflate, br',
//     'accept-language': 'en-US,en;q=0.8,fr;q=0.6' },
//  rawHeaders:
//   [ 'Host',
//     'localhost:8191',
//     'Connection',
//     'keep-alive',
//     'Pragma',
//     'no-cache',
//     'Cache-Control',
//     'no-cache',
//     'User-Agent',
//     'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
//     'Accept',
//     'image/webp,image/apng,image/*,*/*;q=0.8',
//     'DNT',
//     '1',
//     'Referer',
//     'http://localhost:8191/?year=2017&month=July',
//     'Accept-Encoding',
//     'gzip, deflate, br',
//     'Accept-Language',
//     'en-US,en;q=0.8,fr;q=0.6' ],
//  trailers: {},
//  rawTrailers: [],
//  _pendings: [],
//  _pendingIndex: 0,
//  upgrade: false,
//  url: '/favicon.ico',
//  method: 'GET',
//  statusCode: null,
//  statusMessage: null,
//  client:
//   { _connecting: false,
//     _hadError: false,
//     _handle:
//      { fd: 12,
//        reading: true,
//        owner: [Circular],
//        onread: [Function: onread],
//        onconnection: null,
//        writeQueueSize: 0 },
//     _parent: null,
//     _host: null,
//     _readableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        buffer: [],
//        length: 0,
//        pipes: null,
//        pipesCount: 0,
//        flowing: true,
//        ended: false,
//        endEmitted: false,
//        reading: false,
//        sync: false,
//        needReadable: true,
//        emittedReadable: false,
//        readableListening: false,
//        defaultEncoding: 'utf8',
//        ranOut: false,
//        awaitDrain: 0,
//        readingMore: false,
//        decoder: null,
//        encoding: null,
//        resumeScheduled: false },
//     readable: true,
//     domain: null,
//     _events:
//      { end: [Object],
//        finish: [Function: onSocketFinish],
//        _socketEnd: [Function: onSocketEnd],
//        drain: [Object],
//        timeout: [Function],
//        error: [Function: socketOnError],
//        close: [Object],
//        data: [Function: socketOnData] },
//     _maxListeners: undefined,
//     _writableState:
//      { objectMode: false,
//        highWaterMark: 16384,
//        needDrain: false,
//        ending: false,
//        ended: false,
//        finished: false,
//        decodeStrings: false,
//        defaultEncoding: 'utf8',
//        length: 0,
//        writing: false,
//        corked: 0,
//        sync: false,
//        bufferProcessing: false,
//        onwrite: [Function],
//        writecb: null,
//        writelen: 0,
//        bufferedRequest: null,
//        lastBufferedRequest: null,
//        pendingcb: 3,
//        prefinished: false,
//        errorEmitted: false },
//     writable: true,
//     allowHalfOpen: true,
//     destroyed: false,
//     bytesRead: 899,
//     _bytesDispatched: 541,
//     _pendingData: null,
//     _pendingEncoding: '',
//     server:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        _connections: 3,
//        _handle: [Object],
//        _usingSlaves: false,
//        _slaves: [],
//        allowHalfOpen: true,
//        pauseOnConnect: false,
//        httpAllowHalfOpen: false,
//        timeout: 120000,
//        _connectionKey: '4:null:8191' },
//     _idleTimeout: 120000,
//     _idleNext:
//      { [Function: utcDate]
//        _onTimeout: [Function],
//        _idleTimeout: 497,
//        _idleNext: [Object],
//        _idlePrev: [Circular],
//        _idleStart: 207393822 },
//     _idlePrev: { _idleNext: [Circular], _idlePrev: [Object] },
//     _idleStart: 207394207,
//     parser:
//      { '0': [Function: parserOnHeaders],
//        '1': [Function: parserOnHeadersComplete],
//        '2': [Function: parserOnBody],
//        '3': [Function: parserOnMessageComplete],
//        _headers: [],
//        _url: '',
//        socket: [Circular],
//        incoming: [Circular],
//        maxHeaderPairs: 2000,
//        onIncoming: [Function: parserOnIncoming] },
//     _paused: false,
//     read: [Function],
//     _consuming: true,
//     _httpMessage:
//      { domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        output: [],
//        outputEncodings: [],
//        outputCallbacks: [],
//        writable: true,
//        _last: false,
//        chunkedEncoding: true,
//        shouldKeepAlive: true,
//        useChunkedEncodingByDefault: true,
//        sendDate: true,
//        _removedHeader: {},
//        _hasBody: true,
//        _trailer: '',
//        finished: false,
//        _hangupClose: false,
//        _headerSent: true,
//        socket: [Circular],
//        connection: [Circular],
//        _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nDate: Thu, 28 Sep 2017 13:04:35 GMT\r\nConnection: keep-alive\r\nTransfer-Encoding: chunked\r\n\r\n',
//        _headers: null,
//        _headerNames: {},
//        statusMessage: 'OK',
//        statusCode: 200 } },
//  _consuming: false,
//  _dumped: false }
