var MongoClient = require('mongodb').MongoClient;
var url = 'mongodb://localhost:27017/mydb';

MongoClient.connect(url, function(err, db) {
  if (err) throw err;

  var myquery = { address: /^O/ };

  db.collection('customers').deleteMany(myquery, function(err, obj) {
    if (err) throw err;
    console.log(obj.result.n + ' document(s) deleted');
    console.log(obj);
    db.close();

    // output:
//{ result: { ok: 1, n: 2 },
//  connection:
//   { domain: null,
//     _events:
//      { error: [Object],
//        close: [Object],
//        timeout: [Object],
//        parseError: [Object] },
//     _maxListeners: undefined,
//     options:
//      { host: 'localhost',
//        port: 27017,
//        size: 5,
//        connectionTimeout: 30000,
//        socketTimeout: 360000,
//        keepAlive: true,
//        keepAliveInitialDelay: 300000,
//        noDelay: true,
//        ssl: false,
//        checkServerIdentity: true,
//        ca: null,
//        crl: null,
//        cert: null,
//        key: null,
//        passPhrase: null,
//        rejectUnauthorized: false,
//        promoteLongs: true,
//        promoteValues: true,
//        promoteBuffers: false,
//        reconnect: true,
//        reconnectInterval: 1000,
//        reconnectTries: 30,
//        domainsEnabled: false,
//        disconnectHandler: [Object],
//        cursorFactory: [Object],
//        emitError: true,
//        socketOptions: {},
//        clientInfo: [Object],
//        readPreference: [Object],
//        promiseLibrary: [Function: Promise],
//        bson: {} },
//     id: 0,
//     logger: { className: 'Connection' },
//     bson: {},
//     tag: undefined,
//     messageHandler: [Function],
//     maxBsonMessageSize: 67108864,
//     port: 27017,
//     host: 'localhost',
//     family: 4,
//     keepAlive: true,
//     keepAliveInitialDelay: 300000,
//     noDelay: true,
//     connectionTimeout: 30000,
//     socketTimeout: 360000,
//     destroyed: false,
//     domainSocket: false,
//     singleBufferSerializtion: true,
//     serializationFunction: 'toBinUnified',
//     ca: null,
//     crl: null,
//     cert: null,
//     key: null,
//     passphrase: null,
//     ssl: false,
//     rejectUnauthorized: false,
//     checkServerIdentity: true,
//     responseOptions:
//      { promoteLongs: true,
//        promoteValues: true,
//        promoteBuffers: false },
//     flushing: false,
//     queue: [],
//     connection:
//      { _connecting: false,
//        _hadError: false,
//        _handle: [Object],
//        _parent: null,
//        _host: 'localhost',
//        _readableState: [Object],
//        readable: true,
//        domain: null,
//        _events: [Object],
//        _maxListeners: undefined,
//        _writableState: [Object],
//        writable: true,
//        allowHalfOpen: false,
//        destroyed: false,
//        bytesRead: 250,
//        _bytesDispatched: 388,
//        _pendingData: null,
//        _pendingEncoding: '',
//        _idleTimeout: 360000,
//        _idleNext: [Object],
//        _idlePrev: [Object],
//        _idleStart: 95698435,
//        read: [Function],
//        _consuming: true },
//     writeStream: null,
//     hashedName: '29bafad3b32b11dc7ce934204952515ea5984b3c',
//     workItems: [],
//     buffer: null,
//     sizeOfMessage: 0,
//     bytesRead: 0,
//     stubBuffer: null },
//  message:
//   { parsed: true,
//     index: 56,
//     raw: <Buffer 38 00 00 00 6a 80 00 00 02 00 00 00 01 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 14 00 00 00 10 6f 6b 00 01 00 00 00 10 6e ... >,
//     data: <Buffer 38 00 00 00 6a 80 00 00 02 00 00 00 01 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 14 00 00 00 10 6f 6b 00 01 00 00 00 10 6e ... >,
//     bson: {},
//     opts:
//      { promoteLongs: true,
//        promoteValues: true,
//        promoteBuffers: false },
//     length: 56,
//     requestId: 32874,
//     responseTo: 2,
//     responseFlags: 8,
//     cursorId: { _bsontype: 'Long', low_: 0, high_: 0 },
//     startingFrom: 0,
//     numberReturned: 1,
//     documents: [ [Object] ],
//     cursorNotFound: false,
//     queryFailure: false,
//     shardConfigStale: false,
//     awaitCapable: true,
//     promoteLongs: true,
//     promoteValues: true,
//     promoteBuffers: false,
//     hashedName: '29bafad3b32b11dc7ce934204952515ea5984b3c' },
//  deletedCount: 2 }

  });
});
